version: '3.5.2'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'sweatter'
      MYSQL_ROOT_PASSWORD: '1111'
    ports:
      - '3306:3306'
    expose:
      - '3306'
  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025